#ifndef GUARD_BATTLE_ARCADE_H
#define GUARD_BATTLE_ARCADE_H

enum ArcadePanelEffect
{
    ARCADE_EFFECT_NONE,
    ARCADE_EFFECT_CUT_HP_PLAYER,
    ARCADE_EFFECT_CUT_HP_OPPONENT,
    ARCADE_EFFECT_POISON_PLAYER,
    ARCADE_EFFECT_POISON_OPPONENT,
    ARCADE_EFFECT_PARALYZE_PLAYER,
    ARCADE_EFFECT_PARALYZE_OPPONENT,
    ARCADE_EFFECT_BURN_PLAYER,
    ARCADE_EFFECT_BURN_OPPONENT,
    ARCADE_EFFECT_SLEEP_PLAYER,
    ARCADE_EFFECT_SLEEP_OPPONENT,
    ARCADE_EFFECT_FREEZE_PLAYER,
    ARCADE_EFFECT_FREEZE_OPPONENT,
    ARCADE_EFFECT_GIVE_ITEM_PLAYER,
    ARCADE_EFFECT_RAISE_LEVEL_PLAYER,
    ARCADE_EFFECT_WEATHER_SUN,
    ARCADE_EFFECT_WEATHER_RAIN,
    ARCADE_EFFECT_WEATHER_SANDSTORM,
    ARCADE_EFFECT_WEATHER_HAIL,
    ARCADE_EFFECT_TRICK_ROOM,
    ARCADE_EFFECT_TEAM_SWAP,
    ARCADE_EFFECT_GIVE_BP_1,
    ARCADE_EFFECT_GIVE_BP_3,
    ARCADE_EFFECT_SKIP_BATTLE,
};

#define ARCADE_PANEL_COUNT_FAVORABLE 9
#define ARCADE_PANEL_COUNT_NEUTRAL   14
#define ARCADE_ROUND_LENGTH          7 // used by round tracking, Task 5

bool8 Arcade_RollIsFavorableBucket(u8 roll0to99, u8 performanceScore);
enum ArcadePanelEffect Arcade_PickPanelInBucket(u8 roll, bool8 favorable);
enum ArcadePanelEffect Arcade_ChoosePanel(u8 performanceScore);
bool8 Arcade_PanelSkipsBattle(enum ArcadePanelEffect effect);
void Arcade_ApplyPanelEffect(enum ArcadePanelEffect effect);

#endif // GUARD_BATTLE_ARCADE_H
